#!/bin/bash
# auteur : ledudulela
# version: 1.0
# màj : 2015-11-09 21:00 
# objet: lance un fichier.desktop se trouvant dans le répertoire en cours (cf xdg-open OU gtk-launch)
# dépendances: zenity
# # ----------------------------------------------------------------------------------------
currentDir=$(dirname "$0") 
dataFile="$currentDir/launch.dat"
lastEntry=''
if [ -f "$dataFile" ]; then # teste si le fichier existe
	lastEntry=`cat "$dataFile"`
fi

txtEntry=$(zenity --entry --entry-text="$lastEntry" --text="Entrez le nom du lanceur à exécuter (sans .desktop) :" --title="Lanceur" --width=400 --height=40 2>/dev/null)
if [ $? == 1 ]; then # teste si le bouton [Annuler] a été cliqué
	exit 10
else
	if [ ${#txtEntry} == 0 ]; then  # teste si la chaine est vide
		zenity --info --text="Paramètre non valide."
		exit 20
	fi
fi
# ---------------------------------------------------

launcherPath=${currentDir}'/'${txtEntry}'.desktop'
if [ -f "$launcherPath" ]; then # teste si le fichier existe
	#cmdLine=${defaultRunner}' "'${launcherPath}'" 2>/dev/null'
	cmdLine=`sed -nr 's/Exec=(.*)$/\\1/p' ${launcherPath}`
	#zenity --info --text="$cmdLine"
	eval "$cmdLine"
	echo "$txtEntry" > "$dataFile"
else
	zenity --error --text="Le lanceur - ${txtEntry} - est introuvable."
fi
exit 0

